on:
  push:
    branches: [main]
    
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "new-release ${{ steps.generate-uuid.outputs.uuid }}"
          release_name: "new-release ${{ steps.generate-uuid.outputs.uuid }}"
          body_path: "RELEASE_NOTES.md"
          draft: false
          prerelease: false


